version: "3"

services:
  server:
    # build: .
    container_name: 'rsshub-never-die'
    image: ${DOCKER_IMAGE:-caomeiyouren/rsshub-never-die}
    restart: always
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      PORT: 3000
      TZ: "Asia/Shanghai"
    volumes:
      - ./logs:/app/logs
