name = "rsshub-never-die"
# 默认为 Production 环境
main = "dist/app.mjs"
minify = true
compatibility_date = "2024-10-20"
compatibility_flags = ["nodejs_compat"]

[vars]
# 超时时间(ms)
TIMEOUT = 60000
# 最大请求体大小(字节)，默认 100MB
MAX_BODY_SIZE = 104857600
# RSSHub 实例 的 URL 地址，，使用英文逗号分隔。
# 官方实例 https://rsshub.app 不用列出，默认添加。
RSSHUB_NODE_URLS = 'https://rsshub.rssforever.com, https://hub.slarker.me, https://rsshub.pseudoyu.com, https://rsshub.ktachibana.party, https://rsshub.woodland.cafe, https://rss.owo.nz, https://yangzhi.app, https://rsshub.henry.wang, https://rss.peachyjoy.top, https://rsshub.speednet.icu'

[env.dev]
# Development 环境配置
main = "src/app.ts"
minify = false

[observability]
enabled = true
head_sampling_rate = 1 # optional. default = 1.
